# Generated by Django 5.2.9 on 2025-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betadash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Bomet', 'Bomet'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kirinyaga', 'Kirinyaga'), ('Nyeri', 'Nyeri'), ('Kisumu', 'Kisumu'), ('Embu', 'Embu'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Taita Taveta', 'Taita Taveta'), ('Kericho', 'Kericho'), ('Lamu', 'Lamu'), ('Nandi', 'Nandi'), ('Nairobi', 'Nairobi'), ('Homa Bay', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Laikipia', 'Laikipia'), ('Kajiado', 'Kajiado'), ('Uasin Gishu', 'Uasin Gishu'), ('Kakamega', 'Kakamega'), ('Kiambu', 'Kiambu'), ('Nyandarua', 'Nyandarua'), ('Machakos', 'Machakos'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Vihiga', 'Vihiga'), ('Kisii', 'Kisii'), ('Baringo', 'Baringo'), ('Siaya', 'Siaya'), ('Bungoma', 'Bungoma'), ('Makueni', 'Makueni'), ('Busia', 'Busia'), ('Samburu', 'Samburu'), ('Kilifi', 'Kilifi'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Meru', 'Meru'), ('Muranga', 'Muranga'), ('Trans Nzoia', 'Trans Nzoia'), ('Narok', 'Narok'), ('Mandera', 'Mandera'), ('West Pokot', 'West Pokot'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Garissa', 'Garissa'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Turkana', 'Turkana')], max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('diabetes_cases', models.PositiveIntegerField(default=0)),
                ('hypertension_cases', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['county', 'year', 'month'],
                'unique_together': {('county', 'year', 'month')},
            },
        ),
    ]
