# Generated by Django 5.2.9 on 2025-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betadash', '0003_alter_healthrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
