# Generated by Django 6.0.1 on 2026-01-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betadash', '0004_healthrecord_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('overall_scope_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lso_amount_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_trench_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backfilled_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fibre_blown_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
