# Generated by Django 6.0.1 on 2026-01-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalLiteracyProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=100)),
                ('target_value', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Programme Target',
                'ordering': ['programme', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='PublicWiFiHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('installed', 'Installed'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
            ],
            options={
                'verbose_name': 'Public WiFi Hotspot',
                'ordering': ['county', 'location'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ICTDigitalHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('construction', 'Under Construction'), ('completed', 'Completed'), ('operational', 'Operational')], max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
            ],
            options={
                'verbose_name': 'ICT Digital Hub',
                'ordering': ['county', 'period'],
            },
        ),
        migrations.CreateModel(
            name='StudioMashinani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('operational', 'Operational'), ('inactive', 'Inactive')], max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
            ],
            options={
                'verbose_name': 'Studio Mashinani',
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MassMediaTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_trained', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
            ],
            options={
                'verbose_name': 'Mass Media Training',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
        migrations.CreateModel(
            name='FibreLinkDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('km_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
            ],
            options={
                'verbose_name': 'Fibre Link Deployment',
                'ordering': ['period__year', 'period__month'],
                'indexes': [models.Index(fields=['county', 'period'], name='dsh_fibreli_county__3445a5_idx'), models.Index(fields=['link_name'], name='dsh_fibreli_link_na_c9b4f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DigitalLiteracyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained', models.PositiveIntegerField()),
                ('employed', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.digitalliteracyprogramme')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
            ],
            options={
                'verbose_name': 'Digital Literacy Statistic',
                'ordering': ['period', 'county'],
                'unique_together': {('programme', 'county', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StudioProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordings_produced', models.PositiveIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.studiomashinani')),
            ],
            options={
                'verbose_name': 'Studio Production',
                'ordering': ['period'],
                'unique_together': {('studio', 'period')},
            },
        ),
    ]
