# Generated by Django 6.0.1 on 2026-01-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UHCTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(choices=[('sha_onboarded', 'SHA Onboarded'), ('individuals_treated', 'Individuals Treated'), ('amount_disbursed', 'Amount Disbursed'), ('digitized_facilities', 'Health Facilities Digitized')], max_length=50)),
                ('target_value', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
            ],
            options={
                'verbose_name': 'UHC Target',
                'ordering': ['kpi', 'county', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='SHAOnboarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarded_count', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhc.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uhc.uhctarget')),
            ],
            options={
                'verbose_name': 'SHA Onboarded',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SHAIndividualsTreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treated_count', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhc.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uhc.uhctarget')),
            ],
            options={
                'verbose_name': 'SHA Individuals Treated',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SHADisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_disbursed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhc.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uhc.uhctarget')),
            ],
            options={
                'verbose_name': 'SHA Disbursement',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
        migrations.CreateModel(
            name='HealthFacilityDigitized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitized_count', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhc.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uhc.uhctarget')),
            ],
            options={
                'verbose_name': 'Digitized Health Facilities',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
    ]
