# Generated by Django 6.0.1 on 2026-01-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsh', '0001_initial'),
        ('uhc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaindividualstreated',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod'),
        ),
        migrations.AlterField(
            model_name='shadisbursement',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod'),
        ),
        migrations.AlterField(
            model_name='shaonboarded',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod'),
        ),
        migrations.AlterField(
            model_name='healthfacilitydigitized',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod'),
        ),
        migrations.DeleteModel(
            name='ReportingPeriod',
        ),
    ]
