# Generated by Django 6.0.1 on 2026-01-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(choices=[('kenyans_onboarded', 'Kenyans Onboarded'), ('units_completed', 'Units Completed'), ('units_pending', 'Units Pending'), ('units_bought', 'Units Bought')], max_length=50)),
                ('target_value', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
            ],
            options={
                'verbose_name': 'Housing Target',
                'ordering': ['kpi', 'county', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='HousingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], max_length=20)),
                ('unit_count', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.housingtarget')),
            ],
            options={
                'verbose_name': 'Housing Unit',
                'ordering': ['period', 'county', 'status'],
                'unique_together': {('county', 'period', 'status')},
            },
        ),
        migrations.CreateModel(
            name='HousingUnitBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_bought', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.housingtarget')),
            ],
            options={
                'verbose_name': 'Units Bought',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
        migrations.CreateModel(
            name='KenyansOnboarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarded_count', models.PositiveIntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.county')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh.reportingperiod')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.housingtarget')),
            ],
            options={
                'verbose_name': 'Kenyans Onboarded',
                'ordering': ['period', 'county'],
                'unique_together': {('county', 'period')},
            },
        ),
    ]
