# Generated by Django 6.0.1 on 2026-01-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingtarget',
            options={'ordering': ['kpi'], 'verbose_name': 'Housing Target'},
        ),
        migrations.RemoveField(
            model_name='housingtarget',
            name='county',
        ),
        migrations.RemoveField(
            model_name='housingtarget',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='housingtarget',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='housingunitbought',
            name='target',
        ),
        migrations.AlterField(
            model_name='housingtarget',
            name='kpi',
            field=models.CharField(choices=[('kenyans_onboarded', 'Kenyans Onboarded'), ('units', 'Units')], max_length=50),
        ),
    ]
